let products = [
  {
    product_id: "1",
    name: "t-shirt",
    base_image: "https://i.etsystatic.com/44066527/r/il/019e2d/5132345803/il_794xN.5132345803_gm12.jpg",
    category: "clothing",
    brand: "gucci",

    images: [
      { color_code: "#e8c14a", image: "https://i.etsystatic.com/44066527/r/il/5cd1ca/5010633055/il_794xN.5010633055_bus8.jpg" },
      { color_code: "#b9cdd8", image: "https://i.etsystatic.com/44066527/r/il/e4ec25/5010634471/il_794xN.5010634471_i7kb.jpg" },
      { color_code: "#663642", image: "https://i.etsystatic.com/44066527/r/il/de4722/5010635151/il_794xN.5010635151_4og8.jpg" },
      { color_code: "#d6642e", image: "https://i.etsystatic.com/44066527/r/il/23c1a3/4962372928/il_794xN.4962372928_71al.jpg" },
    ],
  },

  {
    product_id: "2",
    name: "ben 10 figure",
    base_image: "https://picsum.photos/200",
    category: "toys",
    brand: "ben 10",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "3",
    name: "star wars figure",
    base_image: "https://picsum.photos/200",
    category: "toys",
    brand: "star wars",
    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "4",
    name: "bucket",
    base_image: "https://picsum.photos/200",
    category: "home",
    brand: "wallmart",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "5",
    name: "scrub brush",
    base_image: "https://picsum.photos/200",
    category: "home",
    brand: "wallmart",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "6",
    name: "shirt",
    base_image: "https://picsum.photos/200",
    category: "clothing",
    brand: "wallmart",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "8",
    name: "t-shirt",
    base_image: "https://picsum.photos/200",
    category: "clothing",
    brand: "wallmart",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "9",
    name: "sweatshirt",
    base_image: "https://picsum.photos/200",
    category: "clothing",
    brand: "wallmart",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "10",
    name: "jacket",
    base_image: "https://picsum.photos/200",
    category: "clothing",
    brand: "nike",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "11",
    name: "air conditioner",
    base_image: "https://picsum.photos/200",
    category: "electronics",
    brand: "singer",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "12",
    name: "bread maker",
    base_image: "https://picsum.photos/200",
    category: "electronics",
    brand: "singer",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "13",
    name: "bulb",
    base_image: "https://picsum.photos/200",
    category: "electronics",
    brand: "lg",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "14",
    name: "blender",
    base_image: "https://picsum.photos/200",
    category: "electronics",
    brand: "lg",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "15",
    name: "balls",
    base_image: "https://picsum.photos/200",
    category: "toys",
    brand: "wallmart",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "16",
    name: "ball pits",
    base_image: "https://picsum.photos/200",
    category: "toys",
    brand: "wallmart",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "17",
    name: "cars",
    base_image: "https://picsum.photos/200",
    category: "toys",
    brand: "wallmart",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "18",
    name: "boats",
    base_image: "https://picsum.photos/200",
    category: "toys",
    brand: "wallmart",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "19",
    name: "bubbles",
    base_image: "https://picsum.photos/200",
    category: "toys",
    brand: "wallmart",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "20",
    name: "balloons",
    base_image: "https://picsum.photos/200",
    category: "toys",
    brand: "wallmart",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "21",
    name: "toilet brush",
    base_image: "https://picsum.photos/200",
    category: "home",
    brand: "wallmart",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "22",
    name: "broom",
    base_image: "https://picsum.photos/200",
    category: "home",
    brand: "wallmart",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "23",
    name: "glass cleaner",
    base_image: "https://picsum.photos/200",
    category: "home",
    brand: "wallmart",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "7",
    name: "pant",
    base_image: "https://picsum.photos/200",
    category: "clothing",
    brand: "nike",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "24",
    name: "mop",
    base_image: "https://picsum.photos/200",
    category: "home",
    brand: "wallmart",
    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },

  {
    product_id: "25",
    name: "dustpan",
    base_image: "https://picsum.photos/200",
    category: "home",
    brand: "wallmart",

    images: [
      { color_code: "#3A7D44", image: "https://picsum.photos/200" },
      { color_code: "#C78C3D", image: "https://picsum.photos/200" },
      { color_code: "#56D9F0", image: "https://picsum.photos/200" },
      { color_code: "#BF24A3", image: "https://picsum.photos/200" },
      { color_code: "#6F9D15", image: "https://picsum.photos/200" },
      { color_code: "#B9538B", image: "https://picsum.photos/200" },
      { color_code: "#6C89C2", image: "https://picsum.photos/200" },
      { color_code: "#C8A663", image: "https://picsum.photos/200" },
      { color_code: "#7E5A1E", image: "https://picsum.photos/200" },
      { color_code: "#2D79E1", image: "https://picsum.photos/200" },
      { color_code: "#5D7D42", image: "https://picsum.photos/200" },
      { color_code: "#CB34D3", image: "https://picsum.photos/200" },
      { color_code: "#5BDD7A", image: "https://picsum.photos/200" },
      { color_code: "#839D3F", image: "https://picsum.photos/200" },
      { color_code: "#3B8D96", image: "https://picsum.photos/200" },
      { color_code: "#D1A51A", image: "https://picsum.photos/200" },
      { color_code: "#A54076", image: "https://picsum.photos/200" },
      { color_code: "#669A33", image: "https://picsum.photos/200" },
      { color_code: "#7E8DBF", image: "https://picsum.photos/200" },
      { color_code: "#E75937", image: "https://picsum.photos/200" },
    ],
  },
];

// to simulate a delay in the api response
async function simulatedDelay() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve();
    }, 1500);
  });
}

export default async function handler(req, res) {
  let page = req.query.page || 1;
  let page_size = req.query.page_size || 20;
  let total_count = products.length;

  await simulatedDelay();
  let results = products.slice((page - 1) * page_size, page * page_size);
  res.status(200).json({
    meta: {
      page: page,
      page_size: page_size,
      total_count: total_count,
    },
    results: results,
  });
}
